version: '3.8'

services:
  gt7-dash-client:
    image: ghcr.io/santidotio/gt7-dash-client:latest
    container_name: gt7-dash-client
    depends_on:
      - server
    networks:
      gt7-dash:
    restart: unless-stopped

  gt7-dash-server:
    container_name: gt7-dash-server
    image: ghcr.io/santidotio/gt7-dash-server:latest
    ports:
      - "9527:9527"
      - "443:443"
      - "33739:33739"
      - "33740:33740/udp"
    environment:
      PLAYSTAION_IP: ${PLAYSTAION_IP}
    volumes:
      - ./certs:/app/certs
    networks:
      gt7-dash:
    restart: unless-stopped
  
  gt7-dash-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: gt7-dash-tunnel
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel run
    networks:
      gt7-dash:
    restart: unless-stopped

networks:
  gt7-dash: