version: '3.8'

services:
  gt7-dash-client:
    image: nginx:alpine
    container_name: gt7-dash-client
    volumes:
      - ./client:/usr/share/nginx/html:ro
    networks:
      gt7-dash:
    restart: unless-stopped

  gt7-dash-server:
    container_name: gt7-dash-server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9527:9527"
      - "443:443"
      - "33739:33739"
      - "33740:33740/udp"
    volumes:
      - ./dist:/app/dist
      - ./certs:/app/certs
    environment:
      PLAYSTAION_IP: ${PLAYSTAION_IP}
    networks:
      gt7-dash:
    restart: unless-stopped
  
  gt7-dash-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: gt7-dash-tunnel
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      gt7-dash:
    restart: unless-stopped

networks:
  gt7-dash: