name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]  # Change to your desired branch(es)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Container registry (ghcr.io)
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push gt7-dash-server image
      - name: Extract metadata (tags, labels) for gt7-dash-server
        id: server_meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ghcr.io/${{ github.repository }}/gt7-dash-server

      - name: Build and push Docker image (gt7-dash-server)
        id: push_server
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .
          push: true
          tags: ${{ steps.server_meta.outputs.tags }}
          labels: ${{ steps.server_meta.outputs.labels }}

      # Build and push gt7-dash-client image
      - name: Extract metadata (tags, labels) for gt7-dash-client
        id: client_meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ghcr.io/${{ github.repository }}/gt7-dash-client

      - name: Build and push Docker image (gt7-dash-client)
        id: push_client
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.client_meta.outputs.tags }}
          labels: ${{ steps.client_meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ github.repository }}/gt7-dash-server:${{ steps.push_server.outputs.digest }}
          subject-digest: ${{ steps.push_server.outputs.digest }}
          push-to-registry: true
        # Repeat for gt7-dash-client attestation
