name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]  # Change to your desired branch(es)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # attestations: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Container registry (ghcr.io)
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push gt7-dash-server image
      - name: Build and push gt7-dash-server image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .  # Build context is the current directory
          push: true
          tags: ghcr.io/santidotio/gt7-dash/server:latest
          file: Dockerfile.server  # Specify Dockerfile name

      # Build and push gt7-dash-client image
      - name: Build and push gt7-dash-client image
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          context: .  # Build context is the current directory
          push: true
          tags: ghcr.io/santidotio/gt7-dash/client:latest
          file: Dockerfile.client  # Specify Dockerfile name


      # - name: Generate artifact attestation
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-name: ghcr.io/santidotio/gt7-dash/server:${{ steps.push_server.outputs.digest }}
      #     subject-digest: ${{ steps.push_server.outputs.digest }}
      #     push-to-registry: true
      #   # Repeat for gt7-dash-client attestation
